all:
	gcc -c main.c
	gcc -c merge.c
	gcc -c partition.c
	gcc -c bubbleSort.c
	gcc -c insertionSort.c
	gcc -c selectionSort.c
	
	gcc main.o merge.o partition.o bubbleSort.o insertionSort.o selectionSort.o -o main
	