all:
	gcc -c main.c
	gcc -c mergeSort.c
	gcc -c quickSort.c
	gcc -c bubbleSort.c
	gcc -c insertionSort.c
	gcc -c selectionSort.c

	gcc main.o mergeSort.o quickSort.o bubbleSort.o insertionSort.o selectionSort.o -o main
	